name: BIS Client CI/CD

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and Deploy Container
        run: |
          docker compose down
          docker compose build --no-cache
          docker compose up -d

      - name: Cleanup unused images
        run: docker image prune -f
